# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(791, 773)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.central_widget)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.shield_port_combo = QtWidgets.QComboBox(self.groupBox)
        self.shield_port_combo.setObjectName("shield_port_combo")
        self.horizontalLayout.addWidget(self.shield_port_combo)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.baud_rate_combo = QtWidgets.QComboBox(self.groupBox)
        self.baud_rate_combo.setObjectName("baud_rate_combo")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.baud_rate_combo.addItem("")
        self.horizontalLayout.addWidget(self.baud_rate_combo)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.micro_index_spin = QtWidgets.QSpinBox(self.groupBox)
        self.micro_index_spin.setMaximum(255)
        self.micro_index_spin.setObjectName("micro_index_spin")
        self.horizontalLayout.addWidget(self.micro_index_spin)
        self.connect_button = QtWidgets.QPushButton(self.groupBox)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.disconnect_button = QtWidgets.QPushButton(self.groupBox)
        self.disconnect_button.setObjectName("disconnect_button")
        self.horizontalLayout.addWidget(self.disconnect_button)
        self.conn_ind = QtWidgets.QWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.conn_ind.sizePolicy().hasHeightForWidth())
        self.conn_ind.setSizePolicy(sizePolicy)
        self.conn_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.conn_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.conn_ind.setStyleSheet("background: \"red\";")
        self.conn_ind.setObjectName("conn_ind")
        self.horizontalLayout.addWidget(self.conn_ind)
        self.verticalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.central_tab = QtWidgets.QTabWidget(self.central_widget)
        self.central_tab.setObjectName("central_tab")
        self.main_view_tab = QtWidgets.QWidget()
        self.main_view_tab.setObjectName("main_view_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.main_view_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.main_view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.location_display_frame = QtWidgets.QFrame(self.frame)
        self.location_display_frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.location_display_frame.sizePolicy().hasHeightForWidth())
        self.location_display_frame.setSizePolicy(sizePolicy)
        self.location_display_frame.setMinimumSize(QtCore.QSize(200, 200))
        self.location_display_frame.setMaximumSize(QtCore.QSize(200, 200))
        self.location_display_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.location_display_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.location_display_frame.setLineWidth(1)
        self.location_display_frame.setObjectName("location_display_frame")
        self.verticalLayout_2.addWidget(self.location_display_frame)
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.control_up_button = QtWidgets.QPushButton(self.groupBox_3)
        self.control_up_button.setMinimumSize(QtCore.QSize(30, 30))
        self.control_up_button.setMaximumSize(QtCore.QSize(30, 30))
        self.control_up_button.setObjectName("control_up_button")
        self.gridLayout_4.addWidget(self.control_up_button, 0, 2, 1, 1)
        self.control_right_button = QtWidgets.QPushButton(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_right_button.sizePolicy().hasHeightForWidth())
        self.control_right_button.setSizePolicy(sizePolicy)
        self.control_right_button.setMinimumSize(QtCore.QSize(30, 30))
        self.control_right_button.setMaximumSize(QtCore.QSize(30, 30))
        self.control_right_button.setObjectName("control_right_button")
        self.gridLayout_4.addWidget(self.control_right_button, 1, 3, 1, 1)
        self.control_left_button = QtWidgets.QPushButton(self.groupBox_3)
        self.control_left_button.setMinimumSize(QtCore.QSize(30, 30))
        self.control_left_button.setMaximumSize(QtCore.QSize(30, 30))
        self.control_left_button.setObjectName("control_left_button")
        self.gridLayout_4.addWidget(self.control_left_button, 1, 0, 1, 1)
        self.control_down_button = QtWidgets.QPushButton(self.groupBox_3)
        self.control_down_button.setMinimumSize(QtCore.QSize(30, 30))
        self.control_down_button.setMaximumSize(QtCore.QSize(30, 30))
        self.control_down_button.setObjectName("control_down_button")
        self.gridLayout_4.addWidget(self.control_down_button, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gridLayout.addWidget(self.frame, 1, 2, 1, 1, QtCore.Qt.AlignTop)
        self.groupBox_2 = QtWidgets.QGroupBox(self.main_view_tab)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scan_ind = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_ind.sizePolicy().hasHeightForWidth())
        self.scan_ind.setSizePolicy(sizePolicy)
        self.scan_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.scan_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.scan_ind.setStyleSheet("background: \"red\";")
        self.scan_ind.setObjectName("scan_ind")
        self.gridLayout_2.addWidget(self.scan_ind, 3, 0, 1, 1)
        self.stitch_ind = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stitch_ind.sizePolicy().hasHeightForWidth())
        self.stitch_ind.setSizePolicy(sizePolicy)
        self.stitch_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.stitch_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.stitch_ind.setStyleSheet("background: \"red\";")
        self.stitch_ind.setObjectName("stitch_ind")
        self.gridLayout_2.addWidget(self.stitch_ind, 4, 0, 1, 1)
        self.count_ind = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_ind.sizePolicy().hasHeightForWidth())
        self.count_ind.setSizePolicy(sizePolicy)
        self.count_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.count_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.count_ind.setStyleSheet("background: \"red\";")
        self.count_ind.setObjectName("count_ind")
        self.gridLayout_2.addWidget(self.count_ind, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 4, 1, 1, 1)
        self.seek_reset = QtWidgets.QPushButton(self.groupBox_2)
        self.seek_reset.setObjectName("seek_reset")
        self.gridLayout_2.addWidget(self.seek_reset, 2, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 1, 1, 1)
        self.scaling_reset = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaling_reset.sizePolicy().hasHeightForWidth())
        self.scaling_reset.setSizePolicy(sizePolicy)
        self.scaling_reset.setObjectName("scaling_reset")
        self.gridLayout_2.addWidget(self.scaling_reset, 0, 3, 1, 1)
        self.calibration_reset = QtWidgets.QPushButton(self.groupBox_2)
        self.calibration_reset.setObjectName("calibration_reset")
        self.gridLayout_2.addWidget(self.calibration_reset, 1, 3, 1, 1)
        self.count_reset = QtWidgets.QPushButton(self.groupBox_2)
        self.count_reset.setObjectName("count_reset")
        self.gridLayout_2.addWidget(self.count_reset, 5, 3, 1, 1)
        self.stitch_reset = QtWidgets.QPushButton(self.groupBox_2)
        self.stitch_reset.setObjectName("stitch_reset")
        self.gridLayout_2.addWidget(self.stitch_reset, 4, 3, 1, 1)
        self.scan_reset = QtWidgets.QPushButton(self.groupBox_2)
        self.scan_reset.setObjectName("scan_reset")
        self.gridLayout_2.addWidget(self.scan_reset, 3, 3, 1, 1)
        self.scaling_bar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaling_bar.sizePolicy().hasHeightForWidth())
        self.scaling_bar.setSizePolicy(sizePolicy)
        self.scaling_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.scaling_bar.setProperty("value", 0)
        self.scaling_bar.setObjectName("scaling_bar")
        self.gridLayout_2.addWidget(self.scaling_bar, 0, 4, 1, 1)
        self.calibration_bar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibration_bar.sizePolicy().hasHeightForWidth())
        self.calibration_bar.setSizePolicy(sizePolicy)
        self.calibration_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.calibration_bar.setProperty("value", 0)
        self.calibration_bar.setObjectName("calibration_bar")
        self.gridLayout_2.addWidget(self.calibration_bar, 1, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 2, 6, 1)
        self.stitch_bar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stitch_bar.sizePolicy().hasHeightForWidth())
        self.stitch_bar.setSizePolicy(sizePolicy)
        self.stitch_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.stitch_bar.setProperty("value", 0)
        self.stitch_bar.setObjectName("stitch_bar")
        self.gridLayout_2.addWidget(self.stitch_bar, 4, 4, 1, 1)
        self.scan_bar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scan_bar.sizePolicy().hasHeightForWidth())
        self.scan_bar.setSizePolicy(sizePolicy)
        self.scan_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.scan_bar.setProperty("value", 0)
        self.scan_bar.setObjectName("scan_bar")
        self.gridLayout_2.addWidget(self.scan_bar, 3, 4, 1, 1)
        self.seek_bar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seek_bar.sizePolicy().hasHeightForWidth())
        self.seek_bar.setSizePolicy(sizePolicy)
        self.seek_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.seek_bar.setProperty("value", 0)
        self.seek_bar.setObjectName("seek_bar")
        self.gridLayout_2.addWidget(self.seek_bar, 2, 4, 1, 1)
        self.count_bar = QtWidgets.QProgressBar(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.count_bar.sizePolicy().hasHeightForWidth())
        self.count_bar.setSizePolicy(sizePolicy)
        self.count_bar.setMinimumSize(QtCore.QSize(150, 0))
        self.count_bar.setProperty("value", 0)
        self.count_bar.setObjectName("count_bar")
        self.gridLayout_2.addWidget(self.count_bar, 5, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.seek_ind = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seek_ind.sizePolicy().hasHeightForWidth())
        self.seek_ind.setSizePolicy(sizePolicy)
        self.seek_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.seek_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.seek_ind.setStyleSheet("background: \"red\";")
        self.seek_ind.setObjectName("seek_ind")
        self.gridLayout_2.addWidget(self.seek_ind, 2, 0, 1, 1)
        self.scaling_ind = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaling_ind.sizePolicy().hasHeightForWidth())
        self.scaling_ind.setSizePolicy(sizePolicy)
        self.scaling_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.scaling_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.scaling_ind.setStyleSheet("background: \"red\";")
        self.scaling_ind.setObjectName("scaling_ind")
        self.gridLayout_2.addWidget(self.scaling_ind, 0, 0, 1, 1)
        self.calibration_ind = QtWidgets.QWidget(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibration_ind.sizePolicy().hasHeightForWidth())
        self.calibration_ind.setSizePolicy(sizePolicy)
        self.calibration_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.calibration_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.calibration_ind.setStyleSheet("background: \"red\";")
        self.calibration_ind.setObjectName("calibration_ind")
        self.gridLayout_2.addWidget(self.calibration_ind, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.main_view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout.setObjectName("formLayout")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.movement_scale_stat = QtWidgets.QLabel(self.groupBox_4)
        self.movement_scale_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.movement_scale_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.movement_scale_stat.setLineWidth(1)
        self.movement_scale_stat.setObjectName("movement_scale_stat")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.movement_scale_stat)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.dish_dim_stat = QtWidgets.QLabel(self.groupBox_4)
        self.dish_dim_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.dish_dim_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.dish_dim_stat.setLineWidth(1)
        self.dish_dim_stat.setObjectName("dish_dim_stat")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dish_dim_stat)
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.current_frame_stat = QtWidgets.QLabel(self.groupBox_4)
        self.current_frame_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.current_frame_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.current_frame_stat.setLineWidth(1)
        self.current_frame_stat.setObjectName("current_frame_stat")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.current_frame_stat)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.elapsed_time_stat = QtWidgets.QLabel(self.groupBox_4)
        self.elapsed_time_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.elapsed_time_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.elapsed_time_stat.setLineWidth(1)
        self.elapsed_time_stat.setObjectName("elapsed_time_stat")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.elapsed_time_stat)
        self.gridLayout.addWidget(self.groupBox_4, 4, 1, 1, 1)
        self.micro_frame = QtWidgets.QFrame(self.main_view_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micro_frame.sizePolicy().hasHeightForWidth())
        self.micro_frame.setSizePolicy(sizePolicy)
        self.micro_frame.setToolTipDuration(-6)
        self.micro_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.micro_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.micro_frame.setLineWidth(1)
        self.micro_frame.setMidLineWidth(0)
        self.micro_frame.setObjectName("micro_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.micro_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.micro_video = QtWidgets.QLabel(self.micro_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micro_video.sizePolicy().hasHeightForWidth())
        self.micro_video.setSizePolicy(sizePolicy)
        self.micro_video.setText("")
        self.micro_video.setObjectName("micro_video")
        self.horizontalLayout_2.addWidget(self.micro_video)
        self.gridLayout.addWidget(self.micro_frame, 1, 0, 1, 2)
        self.central_tab.addTab(self.main_view_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tx_data_ind = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_data_ind.sizePolicy().hasHeightForWidth())
        self.tx_data_ind.setSizePolicy(sizePolicy)
        self.tx_data_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.tx_data_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.tx_data_ind.setStyleSheet("background: \"red\";")
        self.tx_data_ind.setObjectName("tx_data_ind")
        self.gridLayout_3.addWidget(self.tx_data_ind, 3, 0, 1, 1)
        self.ready_ind = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ready_ind.sizePolicy().hasHeightForWidth())
        self.ready_ind.setSizePolicy(sizePolicy)
        self.ready_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.ready_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.ready_ind.setStyleSheet("background: \"red\";")
        self.ready_ind.setObjectName("ready_ind")
        self.gridLayout_3.addWidget(self.ready_ind, 1, 0, 1, 1)
        self.tx_running_ind = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_running_ind.sizePolicy().hasHeightForWidth())
        self.tx_running_ind.setSizePolicy(sizePolicy)
        self.tx_running_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.tx_running_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.tx_running_ind.setStyleSheet("background: \"red\";")
        self.tx_running_ind.setObjectName("tx_running_ind")
        self.gridLayout_3.addWidget(self.tx_running_ind, 2, 0, 1, 1)
        self.connected_ind = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connected_ind.sizePolicy().hasHeightForWidth())
        self.connected_ind.setSizePolicy(sizePolicy)
        self.connected_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.connected_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.connected_ind.setStyleSheet("background: \"red\";")
        self.connected_ind.setObjectName("connected_ind")
        self.gridLayout_3.addWidget(self.connected_ind, 0, 0, 1, 1)
        self.rx_running_ind = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rx_running_ind.sizePolicy().hasHeightForWidth())
        self.rx_running_ind.setSizePolicy(sizePolicy)
        self.rx_running_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.rx_running_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.rx_running_ind.setStyleSheet("background: \"red\";")
        self.rx_running_ind.setObjectName("rx_running_ind")
        self.gridLayout_3.addWidget(self.rx_running_ind, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 3, 1, 1, 1)
        self.rx_data_ind = QtWidgets.QWidget(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rx_data_ind.sizePolicy().hasHeightForWidth())
        self.rx_data_ind.setSizePolicy(sizePolicy)
        self.rx_data_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.rx_data_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.rx_data_ind.setStyleSheet("background: \"red\";")
        self.rx_data_ind.setObjectName("rx_data_ind")
        self.gridLayout_3.addWidget(self.rx_data_ind, 5, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_9.setFlat(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.rx_start_cap_button = QtWidgets.QPushButton(self.groupBox_9)
        self.rx_start_cap_button.setObjectName("rx_start_cap_button")
        self.gridLayout_8.addWidget(self.rx_start_cap_button, 1, 0, 1, 1)
        self.rx_stop_cap_button = QtWidgets.QPushButton(self.groupBox_9)
        self.rx_stop_cap_button.setObjectName("rx_stop_cap_button")
        self.gridLayout_8.addWidget(self.rx_stop_cap_button, 1, 1, 1, 1)
        self.rx_flush_button = QtWidgets.QPushButton(self.groupBox_9)
        self.rx_flush_button.setObjectName("rx_flush_button")
        self.gridLayout_8.addWidget(self.rx_flush_button, 1, 2, 1, 1)
        self.rx_queue_table = QtWidgets.QTableView(self.groupBox_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rx_queue_table.sizePolicy().hasHeightForWidth())
        self.rx_queue_table.setSizePolicy(sizePolicy)
        self.rx_queue_table.setObjectName("rx_queue_table")
        self.gridLayout_8.addWidget(self.rx_queue_table, 0, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_9, 0, 2, 4, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.tx_stop_cap_button = QtWidgets.QPushButton(self.groupBox_6)
        self.tx_stop_cap_button.setObjectName("tx_stop_cap_button")
        self.gridLayout_6.addWidget(self.tx_stop_cap_button, 1, 1, 1, 1)
        self.tx_start_cap_button = QtWidgets.QPushButton(self.groupBox_6)
        self.tx_start_cap_button.setObjectName("tx_start_cap_button")
        self.gridLayout_6.addWidget(self.tx_start_cap_button, 1, 0, 1, 1)
        self.tx_flush_button = QtWidgets.QPushButton(self.groupBox_6)
        self.tx_flush_button.setObjectName("tx_flush_button")
        self.gridLayout_6.addWidget(self.tx_flush_button, 1, 2, 1, 1)
        self.tx_queue_table = QtWidgets.QTableView(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_queue_table.sizePolicy().hasHeightForWidth())
        self.tx_queue_table.setSizePolicy(sizePolicy)
        self.tx_queue_table.setObjectName("tx_queue_table")
        self.gridLayout_6.addWidget(self.tx_queue_table, 0, 0, 1, 3)
        self.gridLayout_5.addWidget(self.groupBox_6, 0, 1, 4, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 1, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox_8)
        self.label_28.setObjectName("label_28")
        self.gridLayout_7.addWidget(self.label_28, 4, 0, 1, 1)
        self.rx_scaling_hook = QtWidgets.QCheckBox(self.groupBox_8)
        self.rx_scaling_hook.setText("")
        self.rx_scaling_hook.setObjectName("rx_scaling_hook")
        self.gridLayout_7.addWidget(self.rx_scaling_hook, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.tx_calib_hook = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_calib_hook.sizePolicy().hasHeightForWidth())
        self.tx_calib_hook.setSizePolicy(sizePolicy)
        self.tx_calib_hook.setText("")
        self.tx_calib_hook.setObjectName("tx_calib_hook")
        self.gridLayout_7.addWidget(self.tx_calib_hook, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.tx_scaling_hook = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_scaling_hook.sizePolicy().hasHeightForWidth())
        self.tx_scaling_hook.setSizePolicy(sizePolicy)
        self.tx_scaling_hook.setText("")
        self.tx_scaling_hook.setObjectName("tx_scaling_hook")
        self.gridLayout_7.addWidget(self.tx_scaling_hook, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.rx_calib_hook = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rx_calib_hook.sizePolicy().hasHeightForWidth())
        self.rx_calib_hook.setSizePolicy(sizePolicy)
        self.rx_calib_hook.setText("")
        self.rx_calib_hook.setObjectName("rx_calib_hook")
        self.gridLayout_7.addWidget(self.rx_calib_hook, 2, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.tx_seek_hook = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_seek_hook.sizePolicy().hasHeightForWidth())
        self.tx_seek_hook.setSizePolicy(sizePolicy)
        self.tx_seek_hook.setText("")
        self.tx_seek_hook.setObjectName("tx_seek_hook")
        self.gridLayout_7.addWidget(self.tx_seek_hook, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.tx_scan_hook = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tx_scan_hook.sizePolicy().hasHeightForWidth())
        self.tx_scan_hook.setSizePolicy(sizePolicy)
        self.tx_scan_hook.setText("")
        self.tx_scan_hook.setObjectName("tx_scan_hook")
        self.gridLayout_7.addWidget(self.tx_scan_hook, 4, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.rx_seek_hook = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rx_seek_hook.sizePolicy().hasHeightForWidth())
        self.rx_seek_hook.setSizePolicy(sizePolicy)
        self.rx_seek_hook.setText("")
        self.rx_seek_hook.setObjectName("rx_seek_hook")
        self.gridLayout_7.addWidget(self.rx_seek_hook, 3, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.rx_scan_hook = QtWidgets.QCheckBox(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rx_scan_hook.sizePolicy().hasHeightForWidth())
        self.rx_scan_hook.setSizePolicy(sizePolicy)
        self.rx_scan_hook.setText("")
        self.rx_scan_hook.setObjectName("rx_scan_hook")
        self.gridLayout_7.addWidget(self.rx_scan_hook, 4, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_27 = QtWidgets.QLabel(self.groupBox_8)
        self.label_27.setObjectName("label_27")
        self.gridLayout_7.addWidget(self.label_27, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_8)
        self.label_26.setObjectName("label_26")
        self.gridLayout_7.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_8)
        self.label_29.setObjectName("label_29")
        self.gridLayout_7.addWidget(self.label_29, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_30 = QtWidgets.QLabel(self.groupBox_8)
        self.label_30.setObjectName("label_30")
        self.gridLayout_7.addWidget(self.label_30, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_5.addWidget(self.groupBox_8, 3, 0, 1, 1, QtCore.Qt.AlignTop)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_7)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox_7)
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.tx_packet_stat = QtWidgets.QLabel(self.groupBox_7)
        self.tx_packet_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.tx_packet_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tx_packet_stat.setLineWidth(1)
        self.tx_packet_stat.setObjectName("tx_packet_stat")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tx_packet_stat)
        self.label_19 = QtWidgets.QLabel(self.groupBox_7)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.tx_byte_stat = QtWidgets.QLabel(self.groupBox_7)
        self.tx_byte_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.tx_byte_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tx_byte_stat.setLineWidth(1)
        self.tx_byte_stat.setObjectName("tx_byte_stat")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.tx_byte_stat)
        self.label_21 = QtWidgets.QLabel(self.groupBox_7)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.rx_packet_stat = QtWidgets.QLabel(self.groupBox_7)
        self.rx_packet_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.rx_packet_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rx_packet_stat.setLineWidth(1)
        self.rx_packet_stat.setObjectName("rx_packet_stat")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.rx_packet_stat)
        self.label_23 = QtWidgets.QLabel(self.groupBox_7)
        self.label_23.setObjectName("label_23")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.rx_byte_stat = QtWidgets.QLabel(self.groupBox_7)
        self.rx_byte_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.rx_byte_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rx_byte_stat.setLineWidth(1)
        self.rx_byte_stat.setObjectName("rx_byte_stat")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rx_byte_stat)
        self.gridLayout_5.addWidget(self.groupBox_7, 1, 0, 1, 1)
        self.central_tab.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_12.setMinimumSize(QtCore.QSize(175, 0))
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName("groupBox_12")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_12)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_31 = QtWidgets.QLabel(self.groupBox_12)
        self.label_31.setObjectName("label_31")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.avg_fps_stat = QtWidgets.QLabel(self.groupBox_12)
        self.avg_fps_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.avg_fps_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.avg_fps_stat.setLineWidth(1)
        self.avg_fps_stat.setObjectName("avg_fps_stat")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.avg_fps_stat)
        self.label_33 = QtWidgets.QLabel(self.groupBox_12)
        self.label_33.setObjectName("label_33")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.total_frame_stat = QtWidgets.QLabel(self.groupBox_12)
        self.total_frame_stat.setFrameShape(QtWidgets.QFrame.Panel)
        self.total_frame_stat.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.total_frame_stat.setLineWidth(1)
        self.total_frame_stat.setObjectName("total_frame_stat")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.total_frame_stat)
        self.gridLayout_9.addWidget(self.groupBox_12, 1, 0, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.res_list = QtWidgets.QListWidget(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.res_list.sizePolicy().hasHeightForWidth())
        self.res_list.setSizePolicy(sizePolicy)
        self.res_list.setObjectName("res_list")
        self.gridLayout_10.addWidget(self.res_list, 0, 0, 1, 2)
        self.set_res_button = QtWidgets.QPushButton(self.groupBox_11)
        self.set_res_button.setObjectName("set_res_button")
        self.gridLayout_10.addWidget(self.set_res_button, 1, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_9.addWidget(self.groupBox_11, 0, 1, 2, 1, QtCore.Qt.AlignTop)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_10)
        self.formLayout_3.setObjectName("formLayout_3")
        self.micro_conn_ind = QtWidgets.QWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.micro_conn_ind.sizePolicy().hasHeightForWidth())
        self.micro_conn_ind.setSizePolicy(sizePolicy)
        self.micro_conn_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.micro_conn_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.micro_conn_ind.setStyleSheet("background: \"red\";")
        self.micro_conn_ind.setObjectName("micro_conn_ind")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.micro_conn_ind)
        self.label_24 = QtWidgets.QLabel(self.groupBox_10)
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_24)
        self.feed_run_ind = QtWidgets.QWidget(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feed_run_ind.sizePolicy().hasHeightForWidth())
        self.feed_run_ind.setSizePolicy(sizePolicy)
        self.feed_run_ind.setMinimumSize(QtCore.QSize(20, 20))
        self.feed_run_ind.setMaximumSize(QtCore.QSize(20, 20))
        self.feed_run_ind.setStyleSheet("background: \"red\";")
        self.feed_run_ind.setObjectName("feed_run_ind")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.feed_run_ind)
        self.label_34 = QtWidgets.QLabel(self.groupBox_10)
        self.label_34.setObjectName("label_34")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_34)
        self.gridLayout_9.addWidget(self.groupBox_10, 0, 0, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_13.sizePolicy().hasHeightForWidth())
        self.groupBox_13.setSizePolicy(sizePolicy)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName("groupBox_13")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_13)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_32 = QtWidgets.QLabel(self.groupBox_13)
        self.label_32.setObjectName("label_32")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.fps_spin = QtWidgets.QSpinBox(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fps_spin.sizePolicy().hasHeightForWidth())
        self.fps_spin.setSizePolicy(sizePolicy)
        self.fps_spin.setObjectName("fps_spin")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fps_spin)
        self.start_feed_button = QtWidgets.QPushButton(self.groupBox_13)
        self.start_feed_button.setObjectName("start_feed_button")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.start_feed_button)
        self.stop_feed_button = QtWidgets.QPushButton(self.groupBox_13)
        self.stop_feed_button.setObjectName("stop_feed_button")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.stop_feed_button)
        self.gridLayout_9.addWidget(self.groupBox_13, 0, 2, 2, 1, QtCore.Qt.AlignLeft)
        self.gridLayout_9.setRowStretch(1, 1)
        self.central_tab.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.central_tab)
        main_window.setCentralWidget(self.central_widget)
        self.main_status_bar = QtWidgets.QStatusBar(main_window)
        self.main_status_bar.setObjectName("main_status_bar")
        main_window.setStatusBar(self.main_status_bar)

        self.retranslateUi(main_window)
        self.central_tab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "MainWindow"))
        self.groupBox.setTitle(_translate("main_window", "Connection"))
        self.label_5.setText(_translate("main_window", "Shield Port:"))
        self.label_18.setText(_translate("main_window", "Shield Baud Rate:"))
        self.baud_rate_combo.setCurrentText(_translate("main_window", "300"))
        self.baud_rate_combo.setItemText(0, _translate("main_window", "300"))
        self.baud_rate_combo.setItemText(1, _translate("main_window", "600"))
        self.baud_rate_combo.setItemText(2, _translate("main_window", "1200"))
        self.baud_rate_combo.setItemText(3, _translate("main_window", "2400"))
        self.baud_rate_combo.setItemText(4, _translate("main_window", "4800"))
        self.baud_rate_combo.setItemText(5, _translate("main_window", "9600"))
        self.baud_rate_combo.setItemText(6, _translate("main_window", "14400"))
        self.baud_rate_combo.setItemText(7, _translate("main_window", "19200"))
        self.baud_rate_combo.setItemText(8, _translate("main_window", "28800"))
        self.baud_rate_combo.setItemText(9, _translate("main_window", "38400"))
        self.baud_rate_combo.setItemText(10, _translate("main_window", "57600"))
        self.baud_rate_combo.setItemText(11, _translate("main_window", "115200"))
        self.label_7.setText(_translate("main_window", "Microscope Index:"))
        self.connect_button.setText(_translate("main_window", "Connect"))
        self.disconnect_button.setText(_translate("main_window", "Disconnect"))
        self.groupBox_3.setTitle(_translate("main_window", "Control"))
        self.control_up_button.setText(_translate("main_window", "^"))
        self.control_right_button.setText(_translate("main_window", ">"))
        self.control_left_button.setText(_translate("main_window", "<"))
        self.control_down_button.setText(_translate("main_window", "V"))
        self.groupBox_2.setTitle(_translate("main_window", "Status"))
        self.label_3.setText(_translate("main_window", "Seek Start"))
        self.label_10.setText(_translate("main_window", "Scan"))
        self.label_11.setText(_translate("main_window", "Stitch"))
        self.seek_reset.setText(_translate("main_window", "Reset"))
        self.label_12.setText(_translate("main_window", "Count"))
        self.scaling_reset.setText(_translate("main_window", "Reset"))
        self.calibration_reset.setText(_translate("main_window", "Reset"))
        self.count_reset.setText(_translate("main_window", "Reset"))
        self.stitch_reset.setText(_translate("main_window", "Reset"))
        self.scan_reset.setText(_translate("main_window", "Reset"))
        self.label_2.setText(_translate("main_window", "Calibration"))
        self.label.setText(_translate("main_window", "Scaling"))
        self.groupBox_4.setTitle(_translate("main_window", "Numbers"))
        self.label_6.setText(_translate("main_window", "Movement Scale:"))
        self.movement_scale_stat.setText(_translate("main_window", "UNKNOWN"))
        self.label_8.setText(_translate("main_window", "Dish Dimentions:"))
        self.dish_dim_stat.setText(_translate("main_window", "UNKNOWN"))
        self.label_4.setText(_translate("main_window", "Current Frame:"))
        self.current_frame_stat.setText(_translate("main_window", "UNKNOWN"))
        self.label_13.setText(_translate("main_window", "Elapsed Time:"))
        self.elapsed_time_stat.setText(_translate("main_window", "UNKNOWN"))
        self.central_tab.setTabText(self.central_tab.indexOf(self.main_view_tab), _translate("main_window", "Scanner"))
        self.groupBox_5.setTitle(_translate("main_window", "Status"))
        self.label_16.setText(_translate("main_window", "Ready"))
        self.label_15.setText(_translate("main_window", "Connected"))
        self.label_14.setText(_translate("main_window", "Rx Running"))
        self.label_9.setText(_translate("main_window", "Tx Running"))
        self.label_20.setText(_translate("main_window", "Tx Data"))
        self.label_22.setText(_translate("main_window", "Rx Data"))
        self.groupBox_9.setTitle(_translate("main_window", "Rx Queue"))
        self.rx_start_cap_button.setText(_translate("main_window", "Start Capture"))
        self.rx_stop_cap_button.setText(_translate("main_window", "Stop Capture"))
        self.rx_flush_button.setText(_translate("main_window", "Flush"))
        self.groupBox_6.setTitle(_translate("main_window", "Tx Queue"))
        self.tx_stop_cap_button.setText(_translate("main_window", "Stop Capture"))
        self.tx_start_cap_button.setText(_translate("main_window", "Start Capture"))
        self.tx_flush_button.setText(_translate("main_window", "Flush"))
        self.groupBox_8.setTitle(_translate("main_window", "Inspect Hooks"))
        self.label_25.setText(_translate("main_window", "Scaling"))
        self.label_28.setText(_translate("main_window", "Scan"))
        self.label_27.setText(_translate("main_window", "Seek Start"))
        self.label_26.setText(_translate("main_window", "Calibration"))
        self.label_29.setText(_translate("main_window", "Tx"))
        self.label_30.setText(_translate("main_window", "Rx"))
        self.groupBox_7.setTitle(_translate("main_window", "Statistics"))
        self.label_17.setText(_translate("main_window", "Tx Packets:"))
        self.tx_packet_stat.setText(_translate("main_window", "0"))
        self.label_19.setText(_translate("main_window", "Tx Bytes:"))
        self.tx_byte_stat.setText(_translate("main_window", "0"))
        self.label_21.setText(_translate("main_window", "Rx Packets:"))
        self.rx_packet_stat.setText(_translate("main_window", "0"))
        self.label_23.setText(_translate("main_window", "Rx Bytes:"))
        self.rx_byte_stat.setText(_translate("main_window", "0"))
        self.central_tab.setTabText(self.central_tab.indexOf(self.tab_2), _translate("main_window", "Movement Control"))
        self.groupBox_12.setTitle(_translate("main_window", "Statistics"))
        self.label_31.setText(_translate("main_window", "Average FPS:"))
        self.avg_fps_stat.setText(_translate("main_window", "0"))
        self.label_33.setText(_translate("main_window", "Total Frame Count:"))
        self.total_frame_stat.setText(_translate("main_window", "0"))
        self.groupBox_11.setTitle(_translate("main_window", "Resolution Control"))
        self.set_res_button.setText(_translate("main_window", "Set Resolution"))
        self.groupBox_10.setTitle(_translate("main_window", "Status"))
        self.label_24.setText(_translate("main_window", "Connected"))
        self.label_34.setText(_translate("main_window", "Feed Running"))
        self.groupBox_13.setTitle(_translate("main_window", "Feed Control"))
        self.label_32.setText(_translate("main_window", "FPS Maximum"))
        self.start_feed_button.setText(_translate("main_window", "Start Feed"))
        self.stop_feed_button.setText(_translate("main_window", "Stop Feed"))
        self.central_tab.setTabText(self.central_tab.indexOf(self.tab), _translate("main_window", "Microscope Control"))
